### ISSUE TITLE
Driver?

### ISSUE THREAD

**Issue by Legnatbird** [BoheSama1999/ZapClient-Windows#1]
Im new on this of cheating, what is my own driver?

**Comment by BoheSama1999** [comment]
Code ur own driver, or get one on github then build it, or buy one from others, it needed be eac bypassed. u can load driver like using kdmapper(if u using this, u need remove the trace to void eac detect it)  or whatever. The driver should can do memory read and write, get module address, and have hid is better, then change Driver.hpp DriverHID.hpp to make Client communication with driver
