### ISSUE TITLE
Is there an update supporting the S23 season?

### ISSUE THREAD

**Issue by Kprobem** [BoheSama1999/ZapClient-Windows#10]

**Comment by fastmatikqcc** [comment]
> _No description provided._

if you have ur own driver with CR3 Shuffle Yes you can't use this source .

**Comment by BoheSama1999** [comment]
Check the S23_Patch branch, may works.☘

**Comment by Kprobem** [comment]
cr3 dtb fix?

**Comment by BoheSama1999** [comment]
That's the job of ur drivers.
