### ISSUE TITLE
cannot open input file

### ISSUE THREAD

**Issue by PositivityVibez** [BoheSama1999/ZapClient-Windows#2]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK1181	cannot open input file 'G:\Windows Kits\10\Lib\10.0.22621.0\um\x64\OpenGL32.Lib'	ZapClient-Windows	C:\Users\NAME\Downloads\ZapClient-Windows-master\LINK	1

**Comment by BoheSama1999** [comment]
fixed

**Comment by t2mpus** [comment]
its not fix I get the same error

**Comment by BoheSama1999** [comment]
> its not fix I get the same error

You should download opengl library
