### ISSUE TITLE
unable to start program

### ISSUE THREAD

**Issue by sdfgkhgfdrteryf** [BoheSama1999/ZapClient-Windows#3]
close this

**Comment by BoheSama1999** [comment]
1.Describe the bug 描述你遇到的问题 A clear and concise description of what the bug is. 简洁有效的说明。

2.To Reproduce 如何重现问题 Steps to reproduce the behavior:

3.Screenshots 如有必要，可以截图说明 If applicable, add screenshots to help explain your problem.

**Comment by shusu4649** [comment]
What is a proprietary driver? I can't solve that mystery.
