### ISSUE TITLE
dont know how to use

### ISSUE THREAD

**Issue by sdfgkhgfdrteryf** [BoheSama1999/ZapClient-Windows#4]
im new to cheating and dont know how to use anything like this could you maybe make a setup tutorial?
and how would i go about getting a driver? and will i need multiple? or just one?

**Comment by BoheSama1999** [comment]
If you don't have any programming knowledge, don't use this project, as it will confuse you, and it's currently aimed at developers

**Comment by mallkorebit** [comment]
> im new to cheating and dont know how to use anything like this could you maybe make a setup tutorial? and how would i go about getting a driver? and will i need multiple? or just one?

update offsets and compile

**Comment by shusu4649** [comment]
ドライバーが必要じゃないんですか？

**Comment by shusu4649** [comment]
> > im new to cheating and dont know how to use anything like this could you maybe make a setup tutorial? and how would i go about getting a driver? and will i need multiple? or just one?
> 
> 
> 
> update offsets and compile

ドライバーが必要じゃないんですか？

**Comment by fastmatikqcc** [comment]
> > > im new to cheating and dont know how to use anything like this could you maybe make a setup tutorial? and how would i go about getting a driver? and will i need multiple? or just one?
> > 
> > 
> > update offsets and compile
> 
> ドライバーが必要じゃないんですか？

I have my A1 driver which works with this source but I need a tester because I have been banned from hwid for a while and the "UnknowSpoof" spoofer does not seem to work.
so if anyone who has a working spoofer and wants to try contact me discord
**discord : aimxpert**
