### ISSUE TITLE
new aimbot method ?

### ISSUE THREAD

**Issue by fastmatikqc** [BoheSama1999/ZapClient-Windows#8]
**is there a way to make the aimbot / triggerbot work without using the driver?
everything works A1 except the aimbot and the triggerbot**

**Comment by shusu4649** [comment]
あなたがつかってるドライバーはなんですか？

**Comment by fastmatikqc** [comment]
> あなたがつかってるドライバーはなんですか？

mine driver ?..

**Comment by BoheSama1999** [comment]
Driver input is a option, but u still could use memory type to change the viewangle(by default)

**Comment by fastmatikqc** [comment]
> Driver input is a option, but u still could use memory type to change the viewangle(by default)

i made working thanks you
